name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            artifact_name: url_scraper_win.exe
            asset_name: url_scraper_win.exe
          - os: macos-latest
            artifact_name: url_scraper_mac
            asset_name: url_scraper_mac

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: |
          python -m PyInstaller --onefile --name ${{ matrix.artifact_name }} src/main.py

      - name: Upload Binary
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-binary
          path: dist/${{ matrix.artifact_name }}

      - name: Upload Scripts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-scripts
          path: |
            scripts/*
            README.txt

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Prepare Release Package
        run: |
          mkdir -p release
          cp artifacts/windows-latest-binary/* release/
          cp artifacts/macos-latest-binary/* release/
          cp -r artifacts/windows-latest-scripts/* release/
          chmod +x release/url_scraper_mac
          chmod +x release/scripts/RUN_ME.command
          cd release
          zip -r ../url-scraper_universal.zip *

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: url-scraper_universal.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 