name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Create distribution directory
        run: mkdir -p dist

      - name: Build executables
        run: |
          # Build Windows executable
          pyinstaller --onefile --name url_scraper_win.exe src/main.py
          mv dist/url_scraper_win.exe dist/
          
          # Build macOS executable
          pyinstaller --onefile --name url_scraper_mac src/main.py
          mv dist/url_scraper_mac dist/
          chmod +x dist/url_scraper_mac

      - name: Prepare distribution package
        run: |
          cp scripts/RUN_ME.bat dist/
          cp scripts/RUN_ME.command dist/
          cp README.txt dist/
          chmod +x dist/RUN_ME.command
          cd dist
          zip -r ../url-scraper_universal.zip *

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: url-scraper_universal.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 