name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Build executable
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            pyinstaller --onefile --name url_scraper_win.exe src/main.py
          else
            pyinstaller --onefile --name url_scraper_mac src/main.py
          fi
          
      - name: Create distribution
        run: |
          mkdir -p dist
          cp scripts/RUN_ME.bat dist/
          cp scripts/RUN_ME.command dist/
          cp README.txt dist/
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            cp dist/url_scraper_win.exe dist/
          else
            cp dist/url_scraper_mac dist/
          fi
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-${{ matrix.os }}
          path: dist/
          
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
          
      - name: Create universal distribution
        run: |
          mkdir -p universal-dist
          cp artifacts/dist-windows-latest/url_scraper_win.exe universal-dist/
          cp artifacts/dist-macos-latest/url_scraper_mac universal-dist/
          cp artifacts/dist-windows-latest/RUN_ME.bat universal-dist/
          cp artifacts/dist-macos-latest/RUN_ME.command universal-dist/
          cp artifacts/dist-windows-latest/README.txt universal-dist/
          cd universal-dist
          zip -r ../url-scraper_universal.zip *
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: url-scraper_universal.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 