name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create distribution directory
        run: mkdir -p dist

      - name: Copy scripts and README
        run: |
          cp scripts/RUN_ME.bat dist/
          cp scripts/RUN_ME.command dist/
          cp README.txt dist/
          chmod +x dist/RUN_ME.command

      - name: Build Windows executable
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: .
          spec: src/main.py
          requirements: requirements.txt

      - name: Build macOS executable
        uses: JackMcKew/pyinstaller-action-macos@main
        with:
          path: .
          spec: src/main.py
          requirements: requirements.txt

      - name: Copy executables
        run: |
          cp dist/windows/url_scraper_win.exe dist/
          cp dist/macos/url_scraper_mac dist/
          chmod +x dist/url_scraper_mac

      - name: Create ZIP package
        run: |
          cd dist
          zip -r ../url-scraper_universal.zip *

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: url-scraper_universal.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 